version: '3.1'

services:

  frontend:
    image: ghcr.io/riccardoomiccioli/riccardo-omiccioli-portfolio-frontend:main
    restart: always
    ports:
      - "127.0.0.1:3000:3000"

  webhook:
    image: ghcr.io/riccardoomiccioli/riccardo-omiccioli-portfolio-webhook:main
    restart: always
    ports:
      - "127.0.0.1:3001:3001"

