version: '3.1'

services:

  frontend:
    container_name: riccardo-omiccioli-portfolio-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "127.0.0.1:3000:3000"

  webhook:
    container_name: riccardo-omiccioli-portfolio-webhook
    build:
      context: ./webhook
      dockerfile: Dockerfile
    restart: always
    ports:
      - "127.0.0.1:3001:3001"

